/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/.well-known/did.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_did_document"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/x509CertificateChain.pem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_cert_chain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_invites"];
        put?: never;
        post: operations["create_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke_invite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/oidc-clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_dataspaces"];
        put?: never;
        post: operations["register_dataspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_all_orgs"];
        put?: never;
        post: operations["create_org_and_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assistant/generate-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generate_script_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assistant/suggest-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["suggest_cqs_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/invite-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_invite_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /v1/auth/me
         * @description Returns the authenticated user's profile, org, and effective role.
         *     Protected by session_required but NOT tenant_context_required.
         */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /v1/auth/workspaces
         * @description Returns the list of dataspaces the authenticated user has access to,
         *     resolved from the `dataspaces` session value to display info via
         *     the dataspaces table. Used by the sidebar instance switcher.
         */
        get: operations["list_workspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cloud-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_accounts"];
        put?: never;
        post: operations["create_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cloud-accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_account"];
        put: operations["update_account"];
        post?: never;
        delete: operations["delete_account"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_connections"];
        put?: never;
        post: operations["create_connection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_connection"];
        put: operations["update_connection"];
        post?: never;
        delete: operations["delete_connection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_connection_files"];
        put: operations["upload_file"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections/{id}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_file_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["rename_conversation"];
        post?: never;
        delete: operations["delete_conversation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_conversation_messages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gaia-x/compliance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_compliance_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gaia-x/comply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["comply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_jobs"];
        put?: never;
        post: operations["create_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_job"];
        put: operations["update_job"];
        post?: never;
        delete: operations["delete_job"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_job_catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_conversations"];
        put?: never;
        post: operations["create_conversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}/dashboard-layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_dashboard_layout"];
        put: operations["save_dashboard_layout"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}/discover/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ask_discover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}/discover/urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["resolve_discover_urls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stream_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/org/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_org_identity"];
        put: operations["update_org_identity"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/org/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_org_invites"];
        put?: never;
        post: operations["create_org_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/org/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke_org_invite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/org/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/org/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_user_role"];
        post?: never;
        delete: operations["remove_user"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scripts/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validate_script"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/ai/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_ai_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/ai/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["save_ai_provider"];
        post?: never;
        delete: operations["delete_ai_provider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/catalog-storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_catalog_storage"];
        put: operations["save_catalog_storage"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_org_settings"];
        put: operations["save_org_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_preferences"];
        put: operations["save_preferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["service_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminInviteEntry: {
            created_at: string;
            expires_at: string;
            org_id: string;
            org_name: string;
            status: string;
            token: string;
        };
        AdminInviteResult: {
            invite_url: string;
            org_id: string;
            org_name: string;
            token: string;
        };
        AiSettingsPayload: {
            api_key: string;
            /** Format: int32 */
            max_tokens?: number | null;
            model?: string | null;
            provider: string;
        };
        AskRequest: {
            conversation_id?: string | null;
            /**
             * @description When true, the LLM acts as a data analyst explaining query results
             *     instead of generating SQL. The question should contain the original
             *     question, SQL, and result rows.
             */
            explain?: boolean;
            provider?: string | null;
            question: string;
            /**
             * @description DuckDB table schema from the frontend (column names, types, sample values).
             *     When provided, this is used as context for SQL generation instead of the
             *     pipeline summary.
             */
            schema?: string | null;
        };
        AskResponse: {
            answer: string;
            code: components["schemas"]["AskResultCode"];
            conversation_id?: string | null;
            reasoning?: string | null;
            /** @description DuckDB SQL query generated by the LLM (executed client-side via DuckDB-WASM). */
            sql?: string | null;
        };
        /**
         * @description Result code for AI ask responses — replaces raw string literals.
         * @enum {string}
         */
        AskResultCode: "success" | "parse_failed" | "query_failed" | "insufficient_credits" | "llm_failed";
        AuthMethodSchema: {
            fields: components["schemas"]["FieldSchema"][];
            label: string;
            name: string;
        };
        CatalogResponse: {
            catalog: string;
        };
        CatalogStoragePayload: {
            base_url: string;
            cloud_account_id: string;
        };
        CloudAccountSummary: {
            auth_method?: string | null;
            fields: {
                [key: string]: string;
            };
            id: string;
            name: string;
            provider_id: string;
        };
        ColumnInfo: {
            data_type: string;
            name: string;
        };
        /** @description Per-column statistics for a vertex property. */
        ColumnStat: {
            /** Format: int64 */
            count: number;
            /** @description Data type: "string", "int64", "double", "boolean", "date". */
            datatype: string;
            /** @description Full predicate IRI. */
            iri: string;
            max?: string | null;
            min?: string | null;
            /** Format: int64 */
            n_unique: number;
            /** @description Short label used as Parquet column name. */
            name: string;
            samples?: string[];
        };
        /** @description A property column of a [`VertexStatus`]. */
        ColumnStatus: {
            /** @description `GraphAr` data-type spelling (`string`, `int64`, `double`, …). */
            data_type: string;
            /** @description Column / predicate local name. */
            name: string;
        };
        CompetencyQuestion: {
            id: string;
            question: string;
            rationale: string;
        };
        ComplianceCredential: {
            issued_at: string;
            name: string;
            raw_json: {
                [key: string]: unknown;
            };
        };
        ComplianceStatus: {
            compliant: boolean;
            credentials: components["schemas"]["ComplianceCredential"][];
            verified_at?: string | null;
        };
        /** @description SSE event emitted during the comply pipeline. */
        ComplyEvent: {
            data?: null | components["schemas"]["ComplyResponse"];
            /** @description Error message (only on failure) */
            error?: string | null;
            /**
             * Format: int32
             * @description Index 0-5, maps to frontend PHASES array
             */
            index: number;
            /** @description Phase name: key_generation, certificate, lrn_request, signing, compliance_submission, complete */
            phase: string;
        };
        /** @description Request body for the one-click comply endpoint. */
        ComplyRequest: {
            /** @description Optional PEM cert chain — fallback if Caddy certs are unavailable. */
            cert_chain_pem?: string | null;
        };
        /** @description Response from the one-click comply endpoint. */
        ComplyResponse: {
            compliance_vc?: {
                [key: string]: unknown;
            };
            compliant: boolean;
            /** @description Error message on failure. */
            error?: string | null;
            /** @description Which phase failed: key_generation, certificate, lrn_request, lp_signing, tc_signing, compliance_submission. */
            failed_phase?: string | null;
            /** @description PEM-encoded private key (auto-download on success). */
            private_key_pem?: string | null;
        };
        Connection: {
            cloud_account_id?: string | null;
            id: string;
            kind: components["schemas"]["ConnectionKind"];
            location_type: components["schemas"]["LocationType"];
            name: string;
            url: string;
        };
        /** @enum {string} */
        ConnectionKind: "data" | "vocab";
        Conversation: {
            created_at: string;
            id: string;
            job_id: string;
            title?: string | null;
        };
        ConversationMessage: {
            code?: string | null;
            content: string;
            conversation_id: string;
            created_at: string;
            data?: null | components["schemas"]["TabularData"];
            explanation?: string | null;
            id: string;
            role: string;
            sql?: string | null;
        };
        CreateCloudAccountRequest: {
            auth_method?: string | null;
            fields: {
                [key: string]: string;
            };
            name: string;
            provider_id: string;
        };
        CreateConnectionRequest: {
            cloud_account_id?: string | null;
            kind: components["schemas"]["ConnectionKind"];
            location_type: components["schemas"]["LocationType"];
            name: string;
            url: string;
        };
        CreateConversationRequest: {
            title?: string | null;
        };
        CreateInviteRequest: {
            org_name: string;
        };
        CreateJobRequest: {
            connection_ids?: string[];
            dcat_enabled?: boolean | null;
            draft?: boolean;
            mode?: null | components["schemas"]["RunMode"];
            name?: string | null;
            pipeline?: null | components["schemas"]["PipelineSummary"];
            script: string;
        };
        CreateOrgAndInviteRequest: {
            name: string;
        };
        CreateOrgInviteRequest: {
            role: string;
        };
        CreateOrgInviteResponse: {
            invite_url: string;
            token: string;
        };
        CreateOrgResponse: {
            id: string;
            name: string;
            status: string;
        };
        /** @description GraphAr-compatible manifest describing a property graph stored as Parquet files. */
        DataManifest: {
            edges?: components["schemas"]["EdgeManifest"][];
            types: components["schemas"]["TypeManifest"][];
        };
        /** @description Typed envelope for successful API responses: `{ "data": T }`. */
        DataResponse_Value: {
            data: unknown;
        };
        Dataspace: {
            client_id: string;
            created_at: string;
            description?: string | null;
            id: string;
            logo?: string | null;
            name: string;
            updated_at: string;
            url: string;
        };
        /** @description Manifest for an edge type (GraphAr v1 ordered adjacency lists). */
        EdgeManifest: {
            /** @description CSR-ordered edge parquet (ordered by source vertex). */
            by_source: string;
            /** @description CSC-ordered edge parquet (ordered by target vertex). */
            by_target: string;
            /** Format: int64 */
            count: number;
            /** @description Full predicate IRI. */
            iri: string;
            /** @description Short edge label (e.g. "knows"). */
            name: string;
            /** @description Source vertex type name. */
            source_type: string;
            /** @description Target vertex type name. */
            target_type: string;
        };
        /** @description One edge type — its CSR/CSC Parquet pair and endpoints. */
        EdgeStatus: {
            /** @description CSR-ordered (`by_source`) Parquet, dataset-relative. */
            by_source: string;
            /** @description CSC-ordered (`by_target`) Parquet, dataset-relative. */
            by_target: string;
            /**
             * Format: int64
             * @description Edge count (Parquet footer metadata); `None` if the count query failed.
             */
            count?: number | null;
            /** @description Destination vertex type. */
            dst_type: string;
            /** @description The edge type / predicate local name. */
            edge_type: string;
            /** @description Source vertex type. */
            src_type: string;
        };
        Field: {
            name: string;
            optional?: boolean;
            type: string;
            uri?: string | null;
            xsd_datatype?: string | null;
        };
        FieldMapping: {
            source: string;
            target: string;
        };
        FieldSchema: {
            default_value?: string | null;
            env_var?: string | null;
            label: string;
            name: string;
            optional?: boolean;
            secret: boolean;
        };
        FileEntry: {
            last_modified?: string | null;
            path: string;
            /** Format: int64 */
            size: number;
        };
        FileSchema: {
            columns: components["schemas"]["ColumnInfo"][];
            connection_name: string;
            file_path: string;
        };
        FileSchemaResponse: {
            columns: components["schemas"]["ColumnInfo"][];
        };
        GenerateRequest: {
            competency_questions: string[];
            domain: string;
            schemas: components["schemas"]["FileSchema"][];
        };
        GenerateResponse: {
            script: string;
        };
        InviteInfoResponse: {
            valid: boolean;
        };
        InviteToken: {
            created_at: string;
            created_by: string;
            expires_at: string;
            org_id: string;
            role: string;
            token: string;
        };
        Job: {
            /** @description Base URL for catalog parquets in promotor storage. */
            catalog_base?: string | null;
            catalog_manifest?: null | components["schemas"]["DataManifest"];
            completed_at?: string | null;
            connection_ids?: string[];
            created_at: string;
            error?: null | components["schemas"]["JobRuntimeError"];
            id: string;
            manifest?: null | components["schemas"]["RunStatus"];
            mode: components["schemas"]["RunMode"];
            name?: string | null;
            pipeline: components["schemas"]["PipelineSummary"];
            /** @description Base URL for RDF Parquet storage (set when job uses Rdf output). */
            rdf_base?: string | null;
            script?: string | null;
            started_at?: string | null;
            status: components["schemas"]["JobStatus"];
        };
        /** @description SSE event emitted by the job runner at each execution phase. */
        JobEvent: {
            error?: string | null;
            /** Format: int32 */
            index: number;
            phase: string;
            /** Format: int32 */
            total: number;
        };
        /**
         * @description Runtime job error — stored in the database as JSON on a failed job.
         *     This is NOT an API error type; it is a serializable record of what went wrong during execution.
         */
        JobRuntimeError: {
            code: string;
            detail?: string | null;
            message: string;
        };
        /** @enum {string} */
        JobStatus: "draft" | "pending" | "running" | "completed" | "failed" | "cancelled";
        /** @enum {string} */
        LocationType: "cloud" | "local";
        /** @description POST /v1/auth/logout */
        LogoutResponse: {
            end_session_url?: string | null;
        };
        MeOrg: {
            id: string;
            name: string;
            role: string;
        };
        MeResponse: {
            effective_role: string;
            email: string;
            first_name: string;
            last_name: string;
            membership_role?: string | null;
            org?: null | components["schemas"]["MeOrg"];
            user_id: string;
        };
        OperationInput: {
            key_fields?: string[];
            source: string;
        };
        OrgIdentityResponse: {
            country: string;
            country_subdivision_code?: string | null;
            legal_name: string;
            registration_number?: string | null;
            registration_number_type?: string | null;
        };
        OrgInviteEntry: {
            created_at: string;
            expires_at: string;
            role: string;
            status: string;
            token: string;
        };
        /**
         * @description An org member — a Keycloak user's membership in a Keasy organization.
         *     Profile fields (email, first_name, last_name) are cached from OIDC tokens.
         */
        OrgMember: {
            email: string;
            first_name: string;
            joined_at: string;
            last_name: string;
            org_id: string;
            role: string;
            user_id: string;
        };
        OrgSettings: {
            /** @description Base URL for catalog parquet storage (e.g. s3://promotor/catalogs/). */
            catalog_base_url?: string | null;
            /** @description Cloud account ID for catalog parquet storage (set by promotor). */
            catalog_cloud_account_id?: string | null;
            catalog_description?: string | null;
            contact_email?: string | null;
            license_uri?: string | null;
            publisher_name: string;
            publisher_uri?: string | null;
        };
        Organization: {
            country: string;
            country_subdivision_code?: string | null;
            created_at: string;
            id: string;
            legal_name: string;
            name: string;
            registration_number?: string | null;
            registration_number_type?: string | null;
            role: string;
            slug: string;
            updated_at: string;
        };
        PipelineInput: {
            fields: components["schemas"]["Field"][];
            name: string;
        };
        PipelineOperation: {
            fields: components["schemas"]["Field"][];
            inputs: components["schemas"]["OperationInput"][];
            kind: string;
            label: string;
        };
        PipelineOutput: {
            destination?: string | null;
            fields: components["schemas"]["Field"][];
            mappings?: components["schemas"]["FieldMapping"][];
            rdf_type?: string | null;
            source?: string | null;
            type_name: string;
        };
        PipelineSummary: {
            inputs: components["schemas"]["PipelineInput"][];
            operations: components["schemas"]["PipelineOperation"][];
            outputs: components["schemas"]["PipelineOutput"][];
        };
        Preferences: {
            accent_color: string;
            font_family: string;
            font_size: string;
            mono_font_family: string;
            mono_font_size: string;
        };
        ProviderEntry: {
            extensions: string[];
            kind: string;
            name: string;
        };
        ProviderSchema: {
            auth_methods: components["schemas"]["AuthMethodSchema"][];
            common_fields: components["schemas"]["FieldSchema"][];
            icon: string;
            id: string;
            label: string;
        };
        RegisterDataspaceResponse: {
            client_id: string;
            client_secret: string;
            description?: string | null;
            id: string;
            logo?: string | null;
            name: string;
            url: string;
        };
        RegisterOidcClientRequest: {
            description?: string | null;
            logo?: string | null;
            name: string;
            url: string;
        };
        RenameConversationRequest: {
            title: string;
        };
        ResolveResponse: {
            files: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        RunMode: "integrated" | "scheduled";
        /** @description The status object `fossil run --output-json` writes to stdout. */
        RunStatus: {
            /** @description Destination URL the `GraphAr` dataset was written under (echoes `--dest`). */
            dest: string;
            /** @description One entry per emitted edge type (empty until a shape/Phase-B adds edges). */
            edges: components["schemas"]["EdgeStatus"][];
            /** @description One entry per emitted vertex type. */
            vertices: components["schemas"]["VertexStatus"][];
        };
        ServiceStatusResponse: {
            base_domain?: string | null;
            gxdch_compliance: boolean;
            gxdch_notary: boolean;
            oidc: boolean;
        };
        SuggestRequest: {
            domain: string;
            schemas: components["schemas"]["FileSchema"][];
        };
        SuggestResponse: {
            competency_questions: components["schemas"]["CompetencyQuestion"][];
        };
        TabularData: {
            column_types: {
                [key: string]: string;
            };
            columns: string[];
            rows: Record<string, never>[];
        };
        /** @description Manifest for a vertex type (one Parquet file per type). */
        TypeManifest: {
            columns: components["schemas"]["ColumnStat"][];
            /** Format: int64 */
            entity_count: number;
            /** @description Full RDF type IRI. */
            iri: string;
            /** @description Short type name (e.g. "person"). */
            name: string;
            /** @description Relative path to vertex Parquet file. */
            vertex_file: string;
        };
        UpdateCloudAccountRequest: {
            auth_method?: string | null;
            fields?: {
                [key: string]: string;
            } | null;
            name?: string | null;
        };
        UpdateConnectionRequest: {
            cloud_account_id?: string | null;
            kind?: null | components["schemas"]["ConnectionKind"];
            location_type?: null | components["schemas"]["LocationType"];
            name?: string | null;
            url?: string | null;
        };
        UpdateJobRequest: {
            name?: string | null;
            script?: string | null;
        };
        UpdateOrgIdentityPayload: {
            country: string;
            country_subdivision_code?: string | null;
            legal_name: string;
            registration_number?: string | null;
            registration_number_type?: string | null;
        };
        UpdateUserRoleRequest: {
            role: string;
        };
        UploadFileRequest: {
            content: string;
            path: string;
        };
        ValidateRequest: {
            script: string;
        };
        ValidationResult: {
            errors: string[];
            pipeline: components["schemas"]["PipelineSummary"];
            valid: boolean;
        };
        /**
         * @description One vertex type — its dataset-relative Parquet, row count, and property
         *     columns.
         */
        VertexStatus: {
            /** @description The vertex's property columns. */
            columns: components["schemas"]["ColumnStatus"][];
            /**
             * Format: int64
             * @description Row count (Parquet footer metadata); `None` if the count query failed.
             */
            count?: number | null;
            /** @description Dataset-relative Parquet path, e.g. `vertex/Person.parquet`. */
            file: string;
            /** @description The vertex type / `GraphAr` `type` (e.g. `Person`). */
            type: string;
        };
        Workspace: {
            client_id: string;
            name: string;
            url: string;
        };
        WorkspacesResponse: {
            current_client_id: string;
            workspaces: components["schemas"]["Workspace"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_did_document: {
        parameters: {
            query?: {
                /** @description Organization ID (dev fallback) */
                org?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DID document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DID document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_cert_chain: {
        parameters: {
            query?: {
                /** @description Organization ID (dev fallback) */
                org?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description X.509 certificate chain PEM */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Certificate chain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_invites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all invite tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminInviteEntry"][];
                };
            };
        };
    };
    create_invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteRequest"];
            };
        };
        responses: {
            /** @description Invite created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminInviteResult"];
                };
            };
            /** @description Insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invite token to revoke */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_dataspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of registered OIDC clients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataspace"][];
                };
            };
        };
    };
    register_dataspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterOidcClientRequest"];
            };
        };
        responses: {
            /** @description OIDC client registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterDataspaceResponse"];
                };
            };
            /** @description Insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_all_orgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all organizations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"][];
                };
            };
        };
    };
    create_org_and_invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgAndInviteRequest"];
            };
        };
        responses: {
            /** @description Organization created with invite */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrgResponse"];
                };
            };
            /** @description Insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generate_script_stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description SSE stream: delta events + complete with GenerateResponse */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description AI provider not configured */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    suggest_cqs_stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestRequest"];
            };
        };
        responses: {
            /** @description SSE stream: delta events + complete with SuggestResponse */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description AI provider not configured */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_invite_info: {
        parameters: {
            query: {
                /** @description Invite token */
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite token validity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteInfoResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful, returns end_session_url */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_workspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of accessible workspaces */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacesResponse"];
                };
            };
        };
    };
    list_accounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of cloud accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudAccountSummary"][];
                };
            };
        };
    };
    create_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCloudAccountRequest"];
            };
        };
        responses: {
            /** @description Cloud account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudAccountSummary"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cloud account ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cloud account details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudAccountSummary"];
                };
            };
            /** @description Cloud account not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cloud account ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCloudAccountRequest"];
            };
        };
        responses: {
            /** @description Cloud account updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudAccountSummary"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cloud account ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cloud account deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_connections: {
        parameters: {
            query?: {
                /** @description Filter by connection type */
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of connections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"][];
                };
            };
        };
    };
    create_connection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectionRequest"];
            };
        };
        responses: {
            /** @description Connection created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            /** @description Invalid connection or container not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_connection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            /** @description Connection not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_connection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConnectionRequest"];
            };
        };
        responses: {
            /** @description Connection updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            /** @description Invalid connection */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connection not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_connection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_connection_files: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of files in the connection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileEntry"][];
                };
            };
            /** @description File listing not supported */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connection not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadFileRequest"];
            };
        };
        responses: {
            /** @description File uploaded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upload not supported */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connection not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upload failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_file_schema: {
        parameters: {
            query: {
                /** @description Relative file path within the connection */
                path: string;
            };
            header?: never;
            path: {
                /** @description Connection ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileSchemaResponse"];
                };
            };
            /** @description Schema inference failed or unsupported file type */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connection not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rename_conversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameConversationRequest"];
            };
        };
        responses: {
            /** @description Conversation renamed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_conversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_conversation_messages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationMessage"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_compliance_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compliance status and credentials */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceStatus"];
                };
            };
        };
    };
    comply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplyRequest"];
            };
        };
        responses: {
            /** @description SSE stream of compliance phases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ComplyEvent"];
                };
            };
            /** @description Prerequisites missing */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    create_job: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Draft job created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Job submitted for execution */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateJobRequest"];
            };
        };
        responses: {
            /** @description Job updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Job is not a draft */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job is still running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_job_catalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DCAT-AP catalog as Turtle (download) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job or catalog not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_conversations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of conversations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"][];
                };
            };
        };
    };
    create_conversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Conversation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
        };
    };
    get_dashboard_layout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard layout */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No layout saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    save_dashboard_layout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Layout saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ask_discover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description AI answer with DuckDB SQL query */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
        };
    };
    resolve_discover_urls: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed URLs for direct Parquet access */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Job not found or no output */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stream_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of job progress events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["JobEvent"];
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_org_identity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Org identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgIdentityResponse"];
                };
            };
            /** @description Organization not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_org_identity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrgIdentityPayload"];
            };
        };
        responses: {
            /** @description Identity updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgIdentityResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_org_invites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of org invite tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgInviteEntry"][];
                };
            };
        };
    };
    create_org_invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgInviteRequest"];
            };
        };
        responses: {
            /** @description Invite created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrgInviteResponse"];
                };
            };
            /** @description Insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_org_invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invite token to revoke */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users in the org */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgMember"][];
                };
            };
        };
    };
    update_user_role: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRoleRequest"];
            };
        };
        responses: {
            /** @description Role updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of available data providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderEntry"][];
                };
            };
        };
    };
    validate_script: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
        };
    };
    list_ai_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of AI providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSettingsPayload"][];
                };
            };
        };
    };
    save_ai_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Provider ID (e.g. anthropic, openai) */
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiSettingsPayload"];
            };
        };
        responses: {
            /** @description Provider saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSettingsPayload"];
                };
            };
            /** @description Unknown provider */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_ai_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Provider ID */
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown provider */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_catalog_storage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog storage config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogStoragePayload"];
                };
            };
            /** @description Not configured */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    save_catalog_storage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogStoragePayload"];
            };
        };
        responses: {
            /** @description Catalog storage saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogStoragePayload"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_org_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSettings"];
                };
            };
            /** @description No settings configured */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    save_org_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgSettings"];
            };
        };
        responses: {
            /** @description Settings saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSettings"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_preferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description UI preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
        };
    };
    save_preferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Preferences"];
            };
        };
        responses: {
            /** @description Preferences saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_schema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider registry schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSchema"][];
                };
            };
        };
    };
    service_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description External service status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatusResponse"];
                };
            };
        };
    };
}
