/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type $Read<T> = {
    readonly $read: T;
};
export type $Write<T> = {
    readonly $write: T;
};
export type Readable<T> = T extends $Write<any> ? never : T extends $Read<infer U> ? Readable<U> : T extends (infer E)[] ? Readable<E>[] : T extends object ? {
    [K in keyof T as NonNullable<T[K]> extends $Write<any> ? never : K]: Readable<T[K]>;
} : T;
export type Writable<T> = T extends $Read<any> ? never : T extends $Write<infer U> ? Writable<U> : T extends (infer E)[] ? Writable<E>[] : T extends object ? {
    [K in keyof T as NonNullable<T[K]> extends $Read<any> ? never : K]: Writable<T[K]>;
} & {
    [K in keyof T as NonNullable<T[K]> extends $Read<any> ? K : never]?: never;
} : T;
export interface paths {
    "/healthz/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The one model call: the browser sends the prompt, the server adds the key
         *     of the model connection and relays the answer as it streams.
         */
        post: operations["complete_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /v1/auth/workspaces
         * @description The one thing the web cannot answer from its own session: the switcher's
         *     list. `Session` carries who you are and what you may do, and the workspaces
         *     claim is neither — so it is read here, off the token this server verified,
         *     rather than copied into a shape the browser would have to be trusted about.
         *
         *     It takes no role extractor: someone authenticated but
         *     holding no role here still needs to be told where they *do* belong.
         */
        get: operations["list_workspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/branding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_branding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_connections"];
        put?: never;
        post: operations["create_connection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_connection"];
        put?: never;
        post?: never;
        delete: operations["delete_connection"];
        options?: never;
        head?: never;
        patch: operations["update_connection"];
        trace?: never;
    };
    "/v1/connections/{name}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vend a read credential over a source connection's prefix — Unity Catalog's
         *     temporary path credentials over an external location. Sources are read,
         *     never written; the sink is reached only through its jobs.
         */
        post: operations["vend_source_credentials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections/{name}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_connection_files"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections/{name}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** LIST a source, WRITE and DELETE under the sink, list a model's provider. */
        post: operations["validate_connection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_credentials"];
        put?: never;
        post: operations["create_credential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credentials/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_credential"];
        put?: never;
        post?: never;
        delete: operations["delete_credential"];
        options?: never;
        head?: never;
        /**
         * Rotation replaces the whole spec, and is committed only if every connection
         *     using the credential still validates with the new one.
         */
        patch: operations["update_credential"];
        trace?: never;
    };
    "/v1/credentials/{name}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe the credential through every connection that uses it, and at `url`. */
        post: operations["validate_credential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every dataset the workspace produced, as the corpus reader named it: the
         *     owner's index over the whole workspace. It carries metadata only; the
         *     member reaches the bytes through the job that made them.
         */
        get: operations["list_datasets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_jobs"];
        put?: never;
        post: operations["create_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_job"];
        put: operations["update_job"];
        post?: never;
        delete: operations["delete_job"];
        options?: never;
        head?: never;
        /**
         * The browser ran the mapping and uploaded the output; this records the
         *     outcome. `Completed` stores the run report verbatim, unread.
         */
        patch: operations["complete_job"];
        trace?: never;
    };
    "/v1/jobs/{id}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vend a credential over the job's dataset, `{sink}/{folder}/`: to read it
         *     once the job has completed, or to write it while the job runs. The store
         *     holds the boundary, so the credential opens nothing else.
         */
        post: operations["vend_job_credentials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_dashboard"];
        put: operations["put_dashboard"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * What the corpus reader found: the relations a finished job's output holds,
         *     their names and the files that carry them, as `@fossil-lang/corpus`
         *     enumerated them in the browser.
         * @description It is a second call and not a field of the completion because naming a
         *     relation is an answer only a reader holding the manifests can give, and the
         *     run report is not that reader. keasy stores the answer verbatim; it is what
         *     the owner's datasets view lists.
         */
        put: operations["publish_relations"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description What a vended credential lets its holder do under its prefix.
         * @enum {string}
         */
        Access: "read" | "write";
        /**
         * @description How this instance looks, as its deployment declares it. Public: the web
         *     reads it to render the login page and the first paint, before anyone has
         *     signed in.
         */
        Branding: {
            default: components["schemas"]["ThemeDefaults"];
            /** @description Members wear the defaults and choose nothing. */
            lock: boolean;
            /** @description The mark the shell shows: a URL or a path the web serves. */
            logo?: string | null;
            /** @description This instance's display name (`KEASY_WORKSPACE_NAME`). */
            name: string;
            /** @description A theme stylesheet to inline on every page. */
            theme_css?: string | null;
            /** @description The theme names members may choose among; empty allows every theme. */
            themes: string[];
        };
        ChatMessage: {
            content: string;
            role: components["schemas"]["ChatRole"];
        };
        /** @enum {string} */
        ChatRole: "user" | "assistant";
        Check: {
            message?: string | null;
            operation: components["schemas"]["Operation"];
            result: components["schemas"]["Outcome"];
        };
        /**
         * @description The browser-driven completion payload (PATCH `/v1/jobs/{id}`): after running
         *     the mapping in the browser (`@fossil-lang/executor`) and writing the output
         *     with the credential vended for the job, the client reports the run's outcome. `manifest` is the
         *     executor's run report, stored verbatim and never read.
         */
        CompleteJobRequest: {
            /** @description The run report for the uploaded output (on `Completed`) — opaque JSON. */
            manifest?: unknown;
            /**
             * @description Why the run failed (on `Failed`): the run's problem, stored verbatim
             *     and opaque.
             */
            problem?: unknown;
            /** @description The terminal (or `Running`) status the client is transitioning the job to. */
            status: components["schemas"]["JobStatus"];
        };
        /**
         * @description One model call. The browser writes the prompt and keeps the conversation;
         *     the server holds the key and relays the answer.
         */
        CompletionRequest: {
            /**
             * @description The model connection to call. May be left out while the workspace has
             *     exactly one.
             */
            connection?: string | null;
            /**
             * Format: int32
             * @description Fewer tokens than the connection allows.
             */
            max_tokens?: number | null;
            /** @description The conversation, oldest first, ending with the user's turn. */
            messages: components["schemas"]["ChatMessage"][];
            system: string;
        };
        /** @enum {string} */
        ConnectionKind: "data" | "vocab";
        ConnectionTarget: {
            storage: components["schemas"]["StorageTarget"];
        } | {
            model: components["schemas"]["ModelTarget"];
        };
        ConnectionView: {
            created_at: string;
            created_by: string;
            credential: string;
            name: string;
            target: components["schemas"]["ConnectionTarget"];
            updated_at: string;
            updated_by: string;
            validation?: null | components["schemas"]["ValidationReport"];
        };
        CreateConnectionRequest: {
            /** @description The credential it signs or calls with; of the same purpose. */
            credential: string;
            /** @description What programs write after `@`, and the connection's key. */
            name: string;
            target: components["schemas"]["ConnectionTarget"];
        };
        CreateCredentialRequest: {
            name: string;
            /**
             * Format: uri
             * @description A storage URL to LIST before the credential is stored. A storage
             *     credential has no location of its own, so without one it is only
             *     checked to build a client.
             */
            probe_url?: string | null;
            spec: components["schemas"]["CredentialSpecInput"];
        };
        CreateJobRequest: {
            draft?: boolean;
            /**
             * @description The folder under the sink the output lands in: lowercase letters,
             *     digits and `-`, at most 63 characters, starting with a letter or digit.
             *     A draft may leave it out; a job to run needs one no other job in the
             *     sink holds.
             */
            folder?: string | null;
            name?: string | null;
            script: string;
            /** @description Where the output lands: the sink connection's name. */
            sink_connection: string;
        };
        /** @description A credential as a request states it, secrets included. */
        CredentialSpecInput: {
            storage: components["schemas"]["StorageCredentialInput"];
        } | {
            model: components["schemas"]["ModelCredentialInput"];
        };
        /** @description A credential as a response shows it: no secret field exists here. */
        CredentialSpecView: {
            storage: components["schemas"]["StorageCredentialView"];
        } | {
            model: components["schemas"]["ModelCredentialView"];
        };
        CredentialView: {
            created_at: string;
            created_by: string;
            name: string;
            spec: components["schemas"]["CredentialSpecView"];
            updated_at: string;
            updated_by: string;
            /** @description The connections that use this credential. */
            used_by: string[];
            validation?: null | components["schemas"]["ValidationReport"];
        };
        CredentialsRequest: {
            access: components["schemas"]["Access"];
        };
        /**
         * @description A job's saved dashboard. `spec` is the dashboard the web's BI kit
         *     serialises (`DashboardSpec`): keasy stores it and hands it back, and never
         *     reads a field of it.
         */
        Dashboard: {
            spec: Record<string, never>;
            updated_at: string;
            /** @description Keycloak `sub` of the member who saved it last. */
            updated_by: string;
        };
        /** @description A completed job's output, as the owner's datasets view lists it. */
        Dataset: {
            completed_at?: string | null;
            job_id: string;
            name?: string | null;
            relations: components["schemas"]["OutputRelation"][];
        };
        /**
         * @description A source is read through `@name/…`; the one sink is where job output lands.
         * @enum {string}
         */
        Direction: "source" | "sink";
        /**
         * @description The body of every 4xx/5xx, and the payload of an SSE `error` frame — the
         *     shape fossil's problems have: a code, its fixed title, a detail for a
         *     person that nothing parses, and the data the code carries.
         */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            data: components["schemas"]["ErrorData"];
            detail: string;
            title: string;
        };
        /**
         * @description Every error the server answers with. Closed: a code the server does not
         *     declare here cannot be sent, and the web keys its copy by this enum.
         * @enum {string}
         */
        ErrorCode: "auth/session_required" | "auth/keys_unavailable" | "rbac/no_membership" | "rbac/insufficient_role" | "rate_limited" | "validation_failed" | "invalid_format" | "not_found" | "forbidden" | "internal_error" | "not_draft" | "not_completed" | "not_running" | "still_running" | "invalid_destination" | "no_destination" | "already_exists" | "in_use" | "overlaps" | "probe_failed" | "list_files_failed" | "store_error" | "ai_not_configured" | "ai_connection_required" | "insufficient_credits" | "llm_failed";
        /** @description What a refusal carries beside its words. */
        ErrorData: {
            /**
             * @description What the refusal is about: what still uses a credential or connection,
             *     or the connections a rotation would break.
             */
            dependents?: string[];
        };
        /** @description One object under a connection's prefix. */
        FileEntry: {
            last_modified?: string | null;
            path: string;
            /** Format: int64 */
            size: number;
        };
        Job: {
            completed_at?: string | null;
            created_at: string;
            /**
             * @description Keycloak `sub` of the member who created the job, and the only one who
             *     may see, change, run or read it. Taken from the token, never the body.
             */
            created_by: string;
            /**
             * @description The folder under the sink the output lands in. A draft may not have one
             *     yet; every other job does, and no two of them share one in a sink.
             */
            folder?: string | null;
            id: string;
            /**
             * @description What the run reported, verbatim and **opaque**: fossil's own run report,
             *     which IS the manifest the corpus carries. keasy stores it, hands it back
             *     and never reads a field of it — the last time a host re-typed this
             *     struct, it ended up asking for `vertex/<Type>.parquet`, a file the
             *     layout pass deletes. Its presence is the one thing keasy asks of it:
             *     "this job produced output".
             */
            manifest?: unknown;
            name?: string | null;
            /**
             * @description Why a `Failed` run failed, as the browser that ran it reported it: a
             *     problem (`{ code, title, detail, data, … }`), stored verbatim and
             *     **opaque** — the web branches on its `code`, the server never does.
             */
            problem?: unknown;
            /**
             * @description What the corpus holds and what it is called, as the corpus reader
             *     enumerated it (`@fossil-lang/corpus`). fossil names every relation and
             *     every file; keasy joins them to the destination it owns and signs them
             *     for reading.
             */
            relations?: components["schemas"]["OutputRelation"][];
            script?: string | null;
            /**
             * @description The sink connection the output lands in, under `{sink.url}/{folder}`,
             *     signed with that connection's credential.
             */
            sink_connection: string;
            started_at?: string | null;
            status: components["schemas"]["JobStatus"];
        };
        /** @enum {string} */
        JobStatus: "draft" | "pending" | "running" | "completed" | "failed" | "cancelled";
        ModelCredentialInput: {
            /** Format: password */
            api_key: $Write<string>;
            /** @enum {string} */
            kind: "anthropic";
        } | {
            /** Format: password */
            api_key: $Write<string>;
            /**
             * Format: uri
             * @description An OpenAI-compatible API root. Empty is `https://api.openai.com/v1`.
             */
            base_url?: string | null;
            /** @enum {string} */
            kind: "openai";
        };
        ModelCredentialView: {
            /** @enum {string} */
            kind: "anthropic";
        } | {
            base_url?: string | null;
            /** @enum {string} */
            kind: "openai";
        };
        ModelTarget: {
            /**
             * Format: int32
             * @description The most tokens an answer may take, unless the call asks for fewer.
             */
            max_tokens?: number | null;
            /**
             * @description The provider's model id. Empty runs the provider's default
             *     (Anthropic: claude-sonnet-4-20250514, OpenAI: gpt-4o).
             */
            model?: string | null;
        };
        /**
         * @description What a probe tried.
         * @enum {string}
         */
        Operation: "list" | "write" | "delete" | "models";
        /** @enum {string} */
        Outcome: "pass" | "fail" | "skip";
        /**
         * @description One addressable relation of a job's output, named by fossil.
         *
         *     `name` is the relation the corpus registers and queries by (`Person`,
         *     `Person_knows_Person`) — **keasy does not compose it**; it is what the
         *     corpus reader answered. `files` are the dataset-relative payload files the
         *     corpus addressing enumerated, `rows` the count it reported and `columns`
         *     what a row carries.
         */
        OutputRelation: {
            columns?: components["schemas"]["RelationColumn"][];
            files?: string[];
            name: string;
            /** Format: int64 */
            rows?: number | null;
        };
        /**
         * @description What the corpus reader enumerated for a finished job (PUT
         *     `/v1/jobs/{id}/relations`). It arrives after completion because naming a
         *     relation is the corpus's answer, not the report's: only a reader with the
         *     manifests in hand can say what the dataset is called and which files carry
         *     it.
         */
        PublishRelationsRequest: {
            relations: components["schemas"]["OutputRelation"][];
        };
        /**
         * @description What a credential, and every connection that uses it, is for.
         * @enum {string}
         */
        Purpose: "storage" | "model";
        PutDashboardRequest: {
            /** @description The dashboard, as the web serialises it: any JSON object. */
            spec: Record<string, never>;
        };
        RelationColumn: {
            /** @description The engine's spelling of the Parquet type (`VARCHAR`, `BIGINT`, …). */
            data_type: string;
            name: string;
        };
        StorageCredentialInput: {
            access_key_id: string;
            /**
             * Format: uri
             * @description MinIO, R2 or a gateway. An `http://` endpoint opts into plain HTTP.
             */
            endpoint?: string | null;
            /**
             * @description AWS's guard against the confused deputy, when the role's trust
             *     policy asks for one.
             */
            external_id?: string | null;
            /** @enum {string} */
            kind: "s3";
            /** @default us-east-1 */
            region?: string;
            /**
             * @description The role keasy assumes to vend a credential scoped to one prefix.
             *     AWS needs it; S3-compatible stores (MinIO, Ceph) ignore it.
             */
            role_arn?: string | null;
            /** Format: password */
            secret_access_key: $Write<string>;
        } | {
            account: string;
            /** Format: password */
            key: $Write<string>;
            /** @enum {string} */
            kind: "azure_account_key";
        } | {
            account: string;
            client_id: string;
            /** Format: password */
            client_secret: $Write<string>;
            /** @enum {string} */
            kind: "azure_service_principal";
            tenant_id: string;
        };
        StorageCredentialView: {
            access_key_id: string;
            endpoint?: string | null;
            external_id?: string | null;
            /** @enum {string} */
            kind: "s3";
            region: string;
            role_arn?: string | null;
        } | {
            account: string;
            /** @enum {string} */
            kind: "azure_account_key";
        } | {
            account: string;
            client_id: string;
            /** @enum {string} */
            kind: "azure_service_principal";
            tenant_id: string;
        };
        StorageTarget: {
            direction?: components["schemas"]["Direction"];
            kind?: components["schemas"]["ConnectionKind"];
            /**
             * Format: uri
             * @description The prefix the connection is: `s3://bucket/prefix/` or `az://container/prefix/`.
             */
            url: string;
        };
        /** @description The day and night themes a visitor starts with; absent leaves the web's own. */
        ThemeDefaults: {
            dark?: string | null;
            light?: string | null;
        };
        UpdateConnectionRequest: {
            credential?: string | null;
            name?: string | null;
            target?: null | components["schemas"]["ConnectionTarget"];
        };
        /**
         * @description A rename, a rotation or both. `spec` replaces the whole spec, secrets
         *     included, and is stored only if every connection using the credential
         *     still validates with it.
         */
        UpdateCredentialRequest: {
            name?: string | null;
            spec?: null | components["schemas"]["CredentialSpecInput"];
        };
        UpdateJobRequest: {
            /** @description The draft's folder under the sink, spelled as on create. */
            folder?: string | null;
            name?: string | null;
            script?: string | null;
        };
        ValidateCredentialRequest: {
            /**
             * Format: uri
             * @description A storage URL to LIST besides the connections that use the credential.
             */
            url?: string | null;
        };
        /** @description One probe of a credential or a connection, check by check. */
        ValidationReport: {
            at: string;
            results: components["schemas"]["Check"][];
        };
        /**
         * @description A credential scoped to one prefix, for a lifetime — Iceberg REST's
         *     `StorageCredential`, keys and all (`s3.access-key-id`, `s3.session-token`,
         *     `s3.session-token-expires-at-ms`, `adls.sas-token.<host>`, …), so any
         *     reader of vended credentials reads it. Handing it out is the point, so
         *     this is the one response type that carries a secret: its values stay
         *     [`SecretString`] until the moment they are written into the response.
         */
        VendedCredential: {
            config: {
                [key: string]: string;
            };
            /** @description The canonical prefix it opens, ending in `/`. */
            prefix: string;
        };
        VendedCredentials: {
            /** @description One per prefix; a reader picks the longest prefix that holds a path. */
            storage_credentials: components["schemas"]["VendedCredential"][];
        };
        /**
         * @description The running build's version, so an operator can see which image a tenant is
         *     on. `git_sha`/`built_at` are stamped at build time (CI sets `KEASY_GIT_SHA`/
         *     `KEASY_BUILT_AT`); `version` is the crate version.
         */
        VersionResponse: {
            built_at?: string | null;
            git_sha?: string | null;
            version: string;
        };
        WorkspacesResponse: {
            /** @description This instance's slug — the "current" entry in the switcher. */
            current: string;
            /**
             * @description This instance's display name (`KEASY_WORKSPACE_NAME`). The other
             *     entries show their slug: an instance only knows its own name.
             */
            current_name: string;
            /**
             * @description Slugs of every workspace the user belongs to, read from the `workspaces`
             *     claim on the token this request carried. The web builds each
             *     `<slug>.<domain>` link.
             */
            workspaces: string[];
        };
    };
    responses: {
        /** @description The caller holds no role this route admits */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description The server failed */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description The identity provider's keys are unreachable */
        KeysUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description The caller exceeded their request rate */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description No verified bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    complete_stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletionRequest"];
            };
        };
        responses: {
            /** @description SSE stream: `delta` frames carry text; an `error` frame carries an ErrorBody; the stream ends when the model does */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description No model connection, or several and none named */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No such connection */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    list_workspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of accessible workspaces */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    get_branding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This instance's declared look */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branding"];
                };
            };
        };
    };
    list_connections: {
        parameters: {
            query?: {
                /** @description Only those of this purpose. */
                purpose?: components["schemas"]["Purpose"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The connections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionView"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    create_connection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectionRequest"];
            };
        };
        responses: {
            /** @description Validated and stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionView"];
                };
            };
            /** @description No such credential, one of the other purpose, or a URL it does not reach */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description A sink by a member, or a source or model by the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description A connection of that name, or a second sink */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The connection did not validate */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    get_connection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The connection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionView"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No such connection */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    delete_connection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Not the caller's to delete */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No such connection */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Jobs wrote their output to it; `dependents` names them */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    update_connection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConnectionRequest"];
            };
        };
        responses: {
            /** @description Validated again and stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionView"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Not the caller's to change */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No such connection */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The connection did not validate */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    vend_source_credentials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description A credential that opens the source's prefix, and only it, for an hour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendedCredentials"];
                };
            };
            /** @description Not a storage source, or an access a source does not give */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No such connection */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            /** @description The store refused to vend */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            503: components["responses"]["KeysUnavailable"];
        };
    };
    list_connection_files: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every object under the connection's prefix */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileEntry"][];
                };
            };
            /** @description Not a storage connection */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No such connection */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            /** @description The store refused the listing */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            503: components["responses"]["KeysUnavailable"];
        };
    };
    validate_connection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The probe's report, stored with the connection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No such connection */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    list_credentials: {
        parameters: {
            query?: {
                /** @description Only those of this purpose. */
                purpose?: components["schemas"]["Purpose"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The credentials, with the connections using each; never a secret */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialView"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    create_credential: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCredentialRequest"];
            };
        };
        responses: {
            /** @description Validated and stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialView"];
                };
            };
            /** @description An invalid name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description A credential of that name exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The credential did not validate */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    get_credential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Credential name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The credential; never a secret */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialView"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No such credential */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    delete_credential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Credential name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Neither its creator nor the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No such credential */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Connections still use it; `dependents` names them */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    update_credential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Credential name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCredentialRequest"];
            };
        };
        responses: {
            /** @description Renamed and/or rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialView"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Neither its creator nor the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No such credential */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description A connection using it would not validate with the new spec; `dependents` names them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    validate_credential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Credential name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateCredentialRequest"];
            };
        };
        responses: {
            /** @description The probe's report, stored with the credential */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No such credential */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    list_datasets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every completed job's output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    list_jobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    create_job: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Draft job created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Job submitted for execution */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description The destination is not a sink, or the folder is missing or misspelled */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Another job writes to that folder already */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    update_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateJobRequest"];
            };
        };
        responses: {
            /** @description Job updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Job is not a draft, or the folder is misspelled */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    delete_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Job is still running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    complete_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteJobRequest"];
            };
        };
        responses: {
            /** @description Job status updated from the browser run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description The job is a draft, which is never run */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    vend_job_credentials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description A credential that opens the job's dataset, and only it, for an hour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendedCredentials"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Read before the job completed, or write while it is not running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            /** @description The store refused to vend */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            503: components["responses"]["KeysUnavailable"];
        };
    };
    get_dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job's saved dashboard, or null when none is saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null | components["schemas"]["Dashboard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    put_dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutDashboardRequest"];
            };
        };
        responses: {
            /** @description Dashboard saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            /** @description The spec is not a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The spec is larger than a dashboard may be */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    publish_relations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRelationsRequest"];
            };
        };
        responses: {
            /** @description Relations stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description A file path outside the dataset */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["KeysUnavailable"];
        };
    };
    version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Running build version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
